version: '3'
services:
  nextjs:
    image: ${DOCKER_IMAGE_PATH}:${CI_COMMIT_SHA}
    # environment:
    #   REACT_APP_STRAPI_URL: ${REACT_APP_STRAPI_URL}
    #   REACT_APP_SURA_URL: ${REACT_APP_SURA_URL}
    #   REACT_APP_SUBSCRIPTION_ID: ${REACT_APP_SUBSCRIPTION_ID} 
    #   REACT_APP_RESOURCE_GROUP_NAME: ${REACT_APP_RESOURCE_GROUP_NAME}
    #   REACT_APP_SERVICE_NAME: ${REACT_APP_SERVICE_NAME}
    #   #REACT_APP_API_VERSION: ${REACT_APP_API_VERSION}
    #   #REACT_APP_HMAC_AUTH_HEADER: ${REACT_APP_HMAC_AUTH_HEADER}
    #   REACT_APP_REMEMBER_KEY: ${REACT_APP_REMEMBER_KEY}
    ports:
      - ${PORT}:8080