version: "3"
services:
  nextjs:
    build: .
    environment:
      REACT_APP_STRAPI_URL: ${REACT_APP_STRAPI_URL}
    #   REACT_APP_AZURE_APIM_URL: ${REACT_APP_AZURE_APIM_URL}
    #   REACT_APP_AZURE_SUBSCRIPTION_ID: ${REACT_APP_AZURE_SUBSCRIPTION_ID}
    #   REACT_APP_AZURE_RESOURCE_GROUP_NAME: ${REACT_APP_AZURE_RESOURCE_GROUP_NAME}
    #   REACT_APP_AZURE_SERVICE_NAME: ${REACT_APP_AZURE_SERVICE_NAME}
    #   #REACT_APP_AZURE_APIM_ADMIN_API_VERSION: ${REACT_APP_AZURE_APIM_ADMIN_API_VERSION}
    #   REACT_APP_REMEMBER_KEY: ${REACT_APP_REMEMBER_KEY}
    ports:
      - ${PORT}:8080
    restart: always
