version: '3'
services:
  nextjs:
    image: registry.gitlab.com/cloudappi/sura/dev-portal-sura-frontend:_VERSION
    environment:
      REACT_APP_STRAPI_URL: ${REACT_APP_STRAPI_URL}
      REACT_APP_SURA_URL: ${REACT_APP_SURA_URL}
      REACT_APP_SUBSCRIPTION_ID: ${REACT_APP_SUBSCRIPTION_ID}
      REACT_APP_RESOURCE_GROUP_NAME: ${REACT_APP_RESOURCE_GROUP_NAME}
      REACT_APP_SERVICE_NAME: ${REACT_APP_SERVICE_NAME}
      'REACT_APP_API_VERSION': ${REACT_APP_API_VERSION}
      REACT_APP_REMEMBER_KEY: ${REACT_APP_REMEMBER_KEY}
      REACT_APP_PRIMARY_KEY: ${REACT_APP_PRIMARY_KEY}
      REACT_APP_APIM_UID: ${REACT_APP_APIM_UID}
      REACT_APP_TOKEN_VALID_DAYS: ${REACT_APP_TOKEN_VALID_DAYS}
      REACT_APP_LIST_API_TOP: ${REACT_APP_LIST_API_TOP}
      REACT_APP_LIST_PRODUCT_APIS_TOP: ${REACT_APP_LIST_PRODUCT_APIS_TOP}
      REACT_APP_LIST_PRODUCT_TOP: ${REACT_APP_LIST_PRODUCT_TOP}
      REACT_APP_LIST_SUBSCRIPTIONS: ${REACT_APP_LIST_SUBSCRIPTIONS}
    ports:
      - $PORT:3000