apiVersion: v1
kind: Service
metadata:
  name: CI_PROJECT_NAME
  labels:
    app: CI_PROJECT_NAME
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: CI_PROJECT_NAME

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: CI_PROJECT_NAME
  labels:
    app: CI_PROJECT_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CI_PROJECT_NAME
  template:
    metadata:
      labels:
        app: CI_PROJECT_NAME
    spec:
      containers:
        - name: CI_PROJECT_NAME
          image: CI_REGISTRY_IMAGE:DEPLOY_VERSION
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "400m"
          imagePullPolicy: Always
      imagePullSecrets:
            - name: gitlab-auth-cloudappi

